version: "3"

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

services:
    workspace:
        image: josiahdahl/php-cli-alpine:latest
        volumes:
            - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}"
        tty: true
        networks:
            - frontend
            - backend
    db:
        image: mariadb:10.4.0-bionic
        volumes:
            - data:/var/lib/mysql"
            - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
        ports:
            - "${DB_PORT}:3306"
        environment:
            - MYSQL_DATABASE=${MARIADB_DATABASE}
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - backend
    php-fpm:
        image: josiahdahl/php-fpm-alpine:latest
        volumes:
            - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}"
        networks:
            - backend
    nginx:
        image: josiahdahl/nginx-alpine:latest
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ./nginx/conf.d:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
        networks:
            - frontend
            - backend
        ports:
            - ${LOCAL_PORT}:80

volumes:
    data:
